### ISSUE TITLE
Modification of Anonymization with field priorization

### ISSUE THREAD

**Issue by sofia-001** [fjoniyz/ganges#75]
Connect every column of Dataset with prio factor

- the priorization determines the information loss
- a high priorization means that not as much information loss is acceptable
- a low priorization represents a field without much imortance for further use

- this priorization depends on the use cases of Ampeers

**Comment by Ralfons-06** [comment]
> - a high priorization means that not as much information loss is acceptable

Does this mean expired clusters are suppressed when their information loss is too high?

> - a low priorization represents a field without much imortance for further use

What should happen when the prio is low? Normal publishing?
